### ISSUE TITLE
中间如果可以设置为百度或其他搜索，而不是gpt问答就好了

### ISSUE THREAD

**Issue by Bclound** [jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab#10]
![image](https://github.com/jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab/assets/57136514/3a8806d2-fc52-4fd6-9233-d6e6492c43c1)
就类似于Infinity 那样

**Comment by jason5ng32** [comment]
理解你的需求，但是 Chrome 其实是可以设置默认搜索引擎的，用地址栏搜索其实更快呀。

**Comment by Bclound** [comment]
> 理解你的需求，但是 Chrome 其实是可以设置默认搜索引擎的，用地址栏搜索其实更快呀。

因为我的习惯是用这里百度，地址栏谷歌哈哈

**Comment by jason5ng32** [comment]
容我想想哈……倒是不难弄
