### ISSUE TITLE
每次打开都会 出现这个，怎么去掉

### ISSUE THREAD

**Issue by liangchaofei** [jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab#11]
![image](https://github.com/jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab/assets/37739354/dd74c4e9-9d58-452a-a5e5-dc9157f45be6)

**Comment by jason5ng32** [comment]
故意的……意思就是，希望你按照说明进行操作，信任苹果的服务器或者搭建本地服务。

**Comment by liangchaofei** [comment]
> 故意的……意思就是，希望你按照说明进行操作，信任苹果的服务器或者搭建本地服务。

操作过，就关闭吧，一直显示这个不好

**Comment by liangchaofei** [comment]
加个关闭按钮吧
