### ISSUE TITLE
可以使用iis或者nginx搭建本地服务器吗？

### ISSUE THREAD

**Issue by zdian** [jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab#12]
试了下，设置一个视频文件目录好像不能用

**Comment by jason5ng32** [comment]
理论上是可以的，你可以参照代码里的 videoserver.conf 文件，修改为 nginx 的配置。需要注意的是，你的配置里，需要允许 Indexes，这样视频文件才能被索引。

**Comment by zhuangdx** [comment]
视频清单是定时更新吗
