### ISSUE TITLE
Does it support Windows?

### ISSUE THREAD

**Issue by AlexLin-T** [jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab#14]
It would feel so good if the start page is dynamic video, but I am a Windows user.

If so, how should I use it?

**Comment by jason5ng32** [comment]
Yes, Windows is supported, just install it from Chrome store, and you will find it works.

**Comment by AlexLin-T** [comment]
> Yes, Windows is supported, just install it from Chrome store, and you will find it works.

So how can I get this videos? I have read your README and it says macOS user can directly download videos in the system. But for Windows user I don't find it.

**Comment by jason5ng32** [comment]
You don't have to download anything, and it will automatically works after you install. Just to follow the popup instruction upon installing.

**Comment by AlexLin-T** [comment]
> You don't have to download anything, and it will automatically works after you install. Just to follow the popup instruction upon installing.

Great. This is so friendly for new-come user. I will try it.
Thanks!
