### ISSUE TITLE
能把名言翻译成中文吗，设置成可选项

### ISSUE THREAD

**Issue by dengzp0102** [jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab#15]
<img width="1192" alt="image" src="https://github.com/jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab/assets/81863538/77f88664-cc57-4ffc-b691-131a230c21ec">

**Comment by jason5ng32** [comment]
当扩展的语言不是英文时，翻译功能或出现。
