### ISSUE TITLE
今天更新后，输入框样式错乱了，如图

### ISSUE THREAD

**Issue by j20cc** [jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab#9]
<img width="1087" alt="image" src="https://github.com/jason5ng32/macOS-Screen-Saver-as-Chrome-New-Tab/assets/29476413/661687d3-bd94-48a6-9fa2-e1b612a00204">

**Comment by jason5ng32** [comment]
已经发现了，之前没测 Windows。已经修复，等待 Google 审核中。预计24-48 小时后更新即可。

**Comment by jason5ng32** [comment]
@j20cc 已修复并发布。
